# Generated by Django 4.2.2 on 2024-02-01 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_customuser_reset_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='verify_code',
            field=models.BooleanField(default=False, verbose_name='Верифицирован ли код?'),
        ),
    ]
