# Generated by Django 4.2.2 on 2024-02-01 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_customuser_verify_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='type_user',
            field=models.CharField(choices=[('преподаватель', 'Преподаватель'), ('учащийся', 'Учащийся')], default='учащийся', max_length=20, verbose_name='Тип пользователя'),
        ),
    ]
