# Generated by Django 4.0.3 on 2024-02-06 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_alter_customuser_type_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='name',
            field=models.CharField(default='mironchikk', max_length=250, verbose_name='ФИО пользователя'),
            preserve_default=False,
        ),
    ]
