# Generated by Django 5.0.2 on 2024-02-08 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_educationmaterial_isprivate'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationmaterial',
            name='type',
            field=models.CharField(max_length=350, null=True, verbose_name='Тип материала'),
        ),
    ]
