# Generated by Django 5.0.2 on 2024-02-08 18:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_materialmark'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationmaterial',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата создания'),
            preserve_default=False,
        ),
    ]
