# Generated by Django 4.2.2 on 2024-02-24 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_educationmaterial_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationmaterial',
            name='author',
            field=models.TextField(blank=True, null=True, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='educationmaterial',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='educationmaterial',
            name='fullName',
            field=models.TextField(blank=True, null=True, verbose_name='Полное название'),
        ),
        migrations.AlterField(
            model_name='educationmaterial',
            name='source',
            field=models.URLField(blank=True, max_length=300, null=True, verbose_name='Источник'),
        ),
    ]
