# Generated by Django 4.2.2 on 2024-02-24 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_educationmaterial_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationmaterial',
            name='source',
            field=models.TextField(blank=True, null=True, verbose_name='Источник'),
        ),
    ]
