# Generated by Django 5.0.2 on 2024-02-07 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationmaterial',
            name='isPrivate',
            field=models.BooleanField(default=False, verbose_name='Приватный ли?'),
        ),
    ]
