# Generated by Django 5.0.2 on 2024-02-07 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_educationmaterial_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationmaterial',
            name='author',
            field=models.CharField(default='qwe', max_length=350, verbose_name='Автор'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='educationmaterial',
            name='source',
            field=models.URLField(default='127.0.0.1/', max_length=300, verbose_name='Источник'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='educationmaterial',
            name='theme',
            field=models.CharField(default='qwe', max_length=350, verbose_name='Тематика/предмет'),
            preserve_default=False,
        ),
    ]
