# Generated by Django 5.0.2 on 2024-02-07 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_educationmaterial_author_educationmaterial_source_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationmaterial',
            name='fullName',
            field=models.CharField(max_length=300, null=True, verbose_name='Полное название'),
        ),
        migrations.AlterField(
            model_name='educationmaterial',
            name='author',
            field=models.CharField(max_length=350, null=True, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='educationmaterial',
            name='description',
            field=models.CharField(max_length=350, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='educationmaterial',
            name='source',
            field=models.URLField(max_length=300, null=True, verbose_name='Источник'),
        ),
    ]
