# Generated by Django 5.0.2 on 2024-02-08 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_educationmaterial_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='educationmaterial',
            name='type',
        ),
        migrations.AddField(
            model_name='educationmaterial',
            name='icon',
            field=models.FileField(blank=True, null=True, upload_to='icons_materials/', verbose_name='Иконка материала'),
        ),
    ]
