# Generated by Django 5.0.2 on 2024-02-08 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_educationmaterial_type_educationmaterial_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationmaterial',
            name='icon',
            field=models.FileField(blank=True, default='icons_materials/default.png', null=True, upload_to='icons_materials/', verbose_name='Иконка материала'),
        ),
    ]
