# Generated by Django 5.0.2 on 2024-02-08 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_educationmaterial_icon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='educationmaterial',
            old_name='isPrivate',
            new_name='isPublic',
        ),
    ]
