# Generated by Django 4.2.2 on 2024-02-01 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_customuser_photo_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='type_user',
            field=models.CharField(choices=[('преподаватель', 'Преподаватель'), ('учащийся', 'Преподаватель')], default='draft', max_length=20, verbose_name='Тип пользователя'),
        ),
    ]
