# Generated by Django 4.2.2 on 2024-02-01 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_customuser_type_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='type_user',
            field=models.CharField(choices=[('преподаватель', 'Преподаватель'), ('учащийся', 'Учащийся')], max_length=20, verbose_name='Тип пользователя'),
        ),
    ]
