# Generated by Django 4.2.2 on 2024-02-01 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_customuser_type_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='reset_code',
            field=models.CharField(default=0, max_length=250, verbose_name='Резервный код'),
            preserve_default=False,
        ),
    ]
