# Generated by Django 4.0.3 on 2024-02-06 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_customuser_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='name',
            field=models.CharField(max_length=250, verbose_name='Уникальное имя пользователя'),
        ),
    ]
